/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_sfjp_webglmol_NDKmol_NdkView */

#ifndef _Included_ra_electrifierz_ChemAR_NdkView
#define _Included_ra_electrifierz_ChemAR_NdkView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_sfjp_webglmol_NDKmol_NdkView
 * Method:    nativeGLInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ra_electrifierz_ChemAR_NdkView_nativeGLInit
  (JNIEnv *, jclass);

/*
 * Class:     jp_sfjp_webglmol_NDKmol_NdkView
 * Method:    nativeGLResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ra_electrifierz_ChemAR_NdkView_nativeGLResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jp_sfjp_webglmol_NDKmol_NdkView
 * Method:    nativeGLRender
 * Signature: (FFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_ra_electrifierz_ChemAR_NdkView_nativeGLRender
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     jp_sfjp_webglmol_NDKmol_NdkView
 * Method:    nativeLoadProtein
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ra_electrifierz_ChemAR_NdkView_nativeLoadProtein
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_sfjp_webglmol_NDKmol_NdkView
 * Method:    nativeLoadSDF
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ra_electrifierz_ChemAR_NdkView_nativeLoadSDF
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_sfjp_webglmol_NDKmol_NdkView
 * Method:    nativeLoadCCP4
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ra_electrifierz_ChemAR_NdkView_nativeLoadCCP4
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_sfjp_webglmol_NDKmol_NdkView
 * Method:    nativeUpdateMap
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ra_electrifierz_ChemAR_NdkView_nativeUpdateMap
  (JNIEnv *, jboolean);


/*
 * Class:     jp_sfjp_webglmol_NDKmol_NdkView
 * Method:    buildScene
 * Signature: (IIIIZZIZZZ)V
 */
JNIEXPORT void JNICALL Java_ra_electrifierz_ChemAR_NdkView_buildScene
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jboolean, jint, jboolean, jboolean, jboolean);

/*
 * Class:     jp_sfjp_webglmol_NDKmol_NdkView
 * Method:    nativeAdjustZoom
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ra_electrifierz_ChemAR_NdkView_nativeAdjustZoom
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
